// Generated by scripts/gen-db-types.ts — do not edit by hand.
import type { Generated } from "kysely";
import type { Temporal } from "temporal-polyfill";

export type CategoryTable = {
	slug: string;
	label: string;
	created_at: Date;
};

export type CommentTable = {
	id: Generated<number>;
	post_slug: string;
	author_github_id: number;
	author_github_username: string;
	author_avatar_url: string;
	content: string;
	is_hidden: boolean;
	created_at: Date;
};

export type KittyThemeTable = {
	id: Generated<number>;
	slug: string;
	name: string;
	author_github_id: number;
	author_github_username: string;
	author_avatar_url: string;
	is_published: boolean;
	forked_from_id: number | null;
	blurb: string | null;
	colors: string;
	created_at: Date;
	modified_at: Date | null;
};

export type NoteTable = {
	id: string;
	description: string | null;
	published_at: Date | null;
	created_at: Date;
};

export type PostTable = {
	slug: string;
	title: string;
	markdown: string;
	preview_markdown: string | null;
	public_at: Temporal.PlainDate | null;
	created_at: Date;
	published_at: Date;
	modified_at: Date | null;
	revision: number;
	locale: "is" | "en";
	hero_image: string | null;
	category_slug: string | null;
};

export type DB = {
	category: CategoryTable;
	comment: CommentTable;
	kitty_theme: KittyThemeTable;
	note: NoteTable;
	post: PostTable;
};
