/**
 * Generates src/db/db-types.generated.ts — the kysely table types derived
 * from the drizzle schema in ../schema.ts (the single source of truth, also
 * feeding drizzle-kit migrations).
 *
 * Why a runtime generator instead of a type-level port of drizzle's Kyselify:
 * drizzle-orm 1.0.0-rc.4 does not expose literal db column names at the type
 * level — even drizzle's own `MapColumnName` resolves to `string` there (the
 * kysely adapter was dropped from the 1.0 line for exactly this reason). The
 * runtime column objects carry everything: `dataType`, `notNull`,
 * `config.autoIncrement`, `enumValues`.
 *
 * The mapping is STORAGE-FAITHFUL, mirroring what actually sits on disk (the
 * blog reads rows raw through kysely and decodes in db.ts):
 *
 *   - "number int53"   → number
 *   - "object date"    → number (timestamp columns store epoch seconds)
 *   - "boolean"        → 0 | 1
 *   - "string"         → string
 *   - "string enum"    → the literal union
 *   - "object json"    → string (JSON text) — $type overrides ignored
 *   - autoIncrement    → Generated<T> (never inserted/updated)
 *
 * Run with `bun run gen:db-types` after changing schema.ts and commit the
 * regenerated file.
 */
import { writeFileSync } from "node:fs";
import { Category, Comment, KittyTheme, Note, Post } from "../schema";

const tables = {
	category: Category,
	comment: Comment,
	kitty_theme: KittyTheme,
	note: Note,
	post: Post,
} as const;

interface ColumnLike {
	readonly name: string;
	readonly dataType: string;
	readonly notNull: boolean;
	readonly enumValues?: readonly string[];
	readonly config: { readonly autoIncrement?: boolean };
}

const isColumn = (value: unknown): value is ColumnLike =>
	typeof value === "object" &&
	value !== null &&
	"name" in value &&
	"dataType" in value &&
	"notNull" in value;

const storageType = (col: ColumnLike): string => {
	switch (col.dataType) {
		case "number int53":
		case "object date":
			return "number";
		case "boolean":
			return "0 | 1";
		case "string":
			return "string";
		case "string enum":
			return (col.enumValues ?? []).map((v) => JSON.stringify(v)).join(" | ");
		case "object json":
			return "string";
		case "bigint":
			return "bigint";
		default:
			throw new Error(`gen-db-types: unmapped dataType "${col.dataType}" on "${col.name}"`);
	}
};

const columnType = (col: ColumnLike): string => {
	const base = storageType(col);
	if (col.config.autoIncrement) return `Generated<${base}>`;
	return col.notNull ? base : `${base} | null`;
};

const tableTypeNames: Record<string, string> = {
	category: "CategoryTable",
	comment: "CommentTable",
	kitty_theme: "KittyThemeTable",
	note: "NoteTable",
	post: "PostTable",
};

const lines: string[] = [
	"// Generated by scripts/gen-db-types.ts — do not edit by hand.",
	'import type { Generated } from "kysely";',
	"",
];

for (const [name, table] of Object.entries(tables)) {
	lines.push(`export type ${tableTypeNames[name]} = {`);
	for (const col of Object.values(table).filter(isColumn)) {
		lines.push(`\t${col.name}: ${columnType(col)};`);
	}
	lines.push("};", "");
}

lines.push("export type DB = {");
for (const name of Object.keys(tables)) {
	lines.push(`\t${name}: ${tableTypeNames[name]};`);
}
lines.push("};", "");

writeFileSync("src/db/db-types.generated.ts", lines.join("\n"));
console.log("wrote src/db/db-types.generated.ts");
