/**
 * Generates src/db/db-types.generated.ts — the kysely table types derived
 * from the drizzle schema in ../schema.ts (the single source of truth, also
 * feeding drizzle-kit migrations).
 *
 * Why a runtime generator instead of a type-level port of drizzle's Kyselify:
 * drizzle-orm 1.0.0-rc.4 does not expose literal db column names at the type
 * level — even drizzle's own `MapColumnName` resolves to `string` there (the
 * kysely adapter was dropped from the 1.0 line for exactly this reason). The
 * runtime column objects carry everything: `dataType`, `notNull`,
 * `config.autoIncrement`, `enumValues`.
 *
 * The mapping is WIRE-FAITHFUL — it describes what the tursopg boundary
 * yields through the pg driver and plugins (the blog reads rows raw through
 * kysely and decodes in db.ts):
 *
 *   - "number int53"   → number
 *   - "object date"    → Date (TIMESTAMP columns; the db.ts parser override
 *     keeps the wall-clock-UTC instant, so no epoch math anywhere)
 *   - "boolean"        → boolean (BOOLEAN columns; db.ts drops the 0|1
 *     override — pg parses native booleans)
 *   - "string"         → string
 *   - "string enum"    → the literal union
 *   - "object json"    → string (JSON text) — $type overrides ignored
 *   - autoIncrement    → Generated<T> (never inserted/updated)
 *
 * Calendar dates (post.public_at, a DATE column) are handled by the
 * boundaryOverrides below: the plain-date plugin yields
 * Temporal.PlainDate, not Date.
 *
 * Run with `bun run gen:db-types` after changing schema.ts and commit the
 * regenerated file.
 */
import { writeFileSync } from "node:fs";
import { Category, Comment, KittyTheme, Note, Post } from "../schema";

const tables = {
	category: Category,
	comment: Comment,
	kitty_theme: KittyTheme,
	note: Note,
	post: Post,
} as const;

interface ColumnLike {
	readonly name: string;
	readonly dataType: string;
	readonly notNull: boolean;
	readonly enumValues?: readonly string[];
	readonly config: { readonly autoIncrement?: boolean };
}

const isColumn = (value: unknown): value is ColumnLike =>
	typeof value === "object" &&
	value !== null &&
	"name" in value &&
	"dataType" in value &&
	"notNull" in value;

const storageType = (col: ColumnLike): string => {
	switch (col.dataType) {
		case "number int53":
			return "number";
		case "object date":
			return "Date";
		case "boolean":
			return "boolean";
		case "string":
			return "string";
		case "string enum":
			return (col.enumValues ?? []).map((v) => JSON.stringify(v)).join(" | ");
		case "object json":
			return "string";
		case "bigint":
			return "bigint";
		default:
			throw new Error(`gen-db-types: unmapped dataType "${col.dataType}" on "${col.name}"`);
	}
};

const columnType = (col: ColumnLike): string => {
	const base = storageType(col);
	if (col.config.autoIncrement) return `Generated<${base}>`;
	return col.notNull ? base : `${base} | null`;
};

/**
 * Columns a plugin marshals at the query boundary. These types say what the
 * query boundary YIELDS, not what sits on disk: the plain-date plugin rewrites
 * `Temporal.PlainDate` to its ISO string for storage and hydrates it back on
 * reads, so `post.public_at` is `Temporal.PlainDate | null` — writes must
 * pass a PlainDate (the plugin's stringification is an implementation detail,
 * not part of the API) and reads hand the fancy type back. Plugin processing
 * is unconditional on every query compiled through the instance (raw queries
 * included), so a plugin-less query path is a compile-time error, not a
 * silent string.
 */
const boundaryOverrides: Record<string, Partial<Record<string, string>>> = {
	post: { public_at: "Temporal.PlainDate | null" },
};

const tableTypeNames: Record<string, string> = {
	category: "CategoryTable",
	comment: "CommentTable",
	kitty_theme: "KittyThemeTable",
	note: "NoteTable",
	post: "PostTable",
};

const lines: string[] = [
	"// Generated by scripts/gen-db-types.ts — do not edit by hand.",
	'import type { Generated } from "kysely";',
	'import type { Temporal } from "temporal-polyfill";',
	"",
];

for (const [name, table] of Object.entries(tables)) {
	const overrides = boundaryOverrides[name] ?? {};
	lines.push(`export type ${tableTypeNames[name]} = {`);
	for (const col of Object.values(table).filter(isColumn)) {
		const override = overrides[col.name];
		lines.push(
			override === undefined
				? `\t${col.name}: ${columnType(col)};`
				: `\t${col.name}: ${override};`,
		);
	}
	lines.push("};", "");
}

lines.push("export type DB = {");
for (const name of Object.keys(tables)) {
	lines.push(`\t${name}: ${tableTypeNames[name]};`);
}
lines.push("};", "");

writeFileSync("src/db/db-types.generated.ts", lines.join("\n"));
console.log("wrote src/db/db-types.generated.ts");
